# Site settings
title: Vexpr
description: >- # this means to ignore newlines until "baseurl:"
  Represent expressions as data structures, then transform them
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vexpr.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

header_pages:
  - docs.markdown
  - cookbook.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
